import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'secondary-fixed-dim': '#a2d48f',
        'on-tertiary-fixed-variant': '#464747',
        'inverse-primary': '#c8c6c5',
        'tertiary-container': '#1b1c1c',
        'surface-container-low': '#f3f3f3',
        'outline-variant': '#c4c7c7',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'on-background': '#1a1c1c',
        'on-secondary-fixed-variant': '#25501a',
        'on-primary-fixed-variant': '#474646',
        surface: '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        tertiary: '#000000',
        'surface-tint': '#5f5e5e',
        secondary: '#3d6930',
        'tertiary-fixed-dim': '#c7c6c6',
        'surface-variant': '#e2e2e2',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f1f1f1',
        'on-primary-container': '#858383',
        'on-primary-fixed': '#1c1b1b',
        'on-tertiary-container': '#848484',
        'primary-fixed': '#e5e2e1',
        'on-secondary-container': '#426f35',
        outline: '#747878',
        'on-secondary-fixed': '#022100',
        'on-primary': '#ffffff',
        background: '#f9f9f9',
        'surface-container': '#eeeeee',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#444748',
        'primary-container': '#1c1b1b',
        'secondary-container': '#bdf1a8',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#e3e2e2',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1b1c1c',
        'inverse-surface': '#2f3131',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'secondary-fixed': '#bdf1a8',
        'on-secondary': '#ffffff',
        primary: '#000000',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'element-gap': '16px',
        'container-max': '1280px',
        gutter: '24px',
        'section-padding': '120px',
      },
      fontFamily: {
        serif: ['"Noto Serif"', 'serif'],
        sans: ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        h1: ['"Noto Serif"', 'serif'],
        h2: ['"Noto Serif"', 'serif'],
        h3: ['"Noto Serif"', 'serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '400' }],
        h2: ['36px', { lineHeight: '1.3', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
